name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        sudo apt update && sudo apt install -y --no-install-recommends python3-setuptools
        pip3 install --upgrade setuptools
        pip3 install wheel

    - name: Build package
      run: python3 setup.py sdist bdist_wheel

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@81e9d935c883d0b210363ab89cf05f3894778450
      with:
        user: __token__
        password: ${{ secrets.pypi_password }}

  coverage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        sudo apt update && sudo apt install -y --no-install-recommends python3-setuptools
        pip3 install --upgrade setuptools
        pip3 install coverage

    - name: Test Python
      run: |
        python3 -m coverage run  --source canonicalwebteam ./setup.py test
        poetry run coverage xml

    - uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
